[workspace]
resolver = "3"
members = ["app", "lib", "proto"]

[workspace.dependencies]
anyhow = "1.0.104"
console_error_panic_hook = "0.1"
console_log = "1.0"
env_logger = "0.11.11"
jiff = "0.2.37"
lib = { path = "lib" }
log = "0.4.33"
proto = { path = "proto" }
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4.78"
web-sys = { version = "0.3.105", features = ["HtmlCanvasElement"] }
wgpu = { version = "30", default-features = false }
winit = { version = "0.30", features = [] }
