[package]
name = "app"
version = "0.1.0"
edition = "2024"
autobins = false

[features]
default = []
native-cli = ["dep:tokio"]

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "app-cli"
path = "src/main.rs"
required-features = ["native-cli"]

[dependencies]
anyhow = "1.0.104"
lib = { path = "../lib" }
winit = { version = "0.30", features = [] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4.78"
