[package]
name = "lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
jiff.workspace = true
log.workspace = true
proto.workspace = true
winit.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = { workspace = true, features = ["wgsl", "vulkan", "std", "wgpu-core"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { workspace = true, features = ["wgsl", "webgpu", "std", "web"] }
